### ISSUE TITLE
Content only showing up on the post itself

### ISSUE THREAD

**Issue by baasdesign** [rustygeldmacher/jekyll-contentblocks#11]
I added a contentblock with content to a post in _posts and I included the block in default.html in _layouts with: `{% contentblock article %}`

The content in the contentblock is a small unordered-list (markdown format) just like your example. When I go to the post where the contentblock was specified, the list shows up. When I go to any other page it doesn't.

The weird thing is: 

It does render the contentblock in the order relative to other elements in the default.html layout. When I include it beneath the footer in the default.html layout, the contentblock will show up beneath the footer, but only on the page where I specified the contentblock.

So the contentblock doesn't show up on other pages / posts. But it does obey the order relative to other html elemtents in the default.html layout.

Any thoughts?

**Comment by rustygeldmacher** [comment]
Hi @baasdesign -- if I understand you correctly, you are expecting o define content for a block in one post, and have that content show up on the pages for all posts?

The content for a block will only show up on pages that include `{% contentfor %}` declarations, and it will show up on those pages only. So if you want to include content on all posts pages by using a content block, it sounds like you'll need an intermediate `post.html` layout sets the block's content, and from which all post pages derive.

**Comment by baasdesign** [comment]
I understand now. I was thinking the wrong way around. I used twig a while back, and with Twig I could set content blocks and use them everywhere :)

But I see the usefulness of this way of working aswell! Thanks for explaining.
