### ISSUE TITLE
If statement when false still shows contents

### ISSUE THREAD

**Issue by nandorocker** [rustygeldmacher/jekyll-contentblocks#12]
Trying to hide the `figure` element when there's no header image, but even if the markdown file doesn't have that block, it still shows. No clue why!

```html
	{% capture headerImage %}{% contentblock header-image %}{% endcapture %}
	{% if headerImage != '' %}
		<!-- Header image -->
		<figure class="header-image">
		{{ headerImage }}
		</figure>
	{% endif %}
```

**Comment by aadesh** [comment]
I'm facing the same issue. Is there a work around for this?

**Comment by rustygeldmacher** [comment]
Hi @nandorocker and @aadesh -- I just pushed version 1.0.0 to Rubygems, which has support for `ifhascontent` and `ifnothascontent`. Using those new tags should replace the need for using captures. Let me know how it goes!
