### ISSUE TITLE
Using content blocks anywhere

### ISSUE THREAD

**Issue by thegregthomp** [rustygeldmacher/jekyll-contentblocks#13]
This is kind of a branch off of https://github.com/rustygeldmacher/jekyll-contentblocks/issues/11 But my issue is that I'd love to use a contentblock in my loop of posts on the homepage. 

in my post I'd have something like: 
```
{% contentfor otherstuff %}
* Some content
{% endcontentfor %}
```

and In my index.html something like:

```
  {% for post in site.posts %}
    {% contentblock otherstuff %}
  {% endfor %}
```

But I noticed this doesn't work and using ` {% contentblock otherstuff %}` only works on the post.html layout

**Comment by rustygeldmacher** [comment]
Hi @thegregthomp -- I'm not sure this is possible, because in your example the post hasn't been rendered yet so there's no way for the loop to know what the content is for `otherstuff`.
