### ISSUE TITLE
Markdown not processed from a collection

### ISSUE THREAD

**Issue by tlinkner** [rustygeldmacher/jekyll-contentblocks#14]
I noticed that when I use content blocks from a markdown file in a collection the markdown in the content block isn't processed. Markdown is being transformed for {{ content }}, just not in {% contentblock sidebar %};. Everything is working fine in posts. Any ideas?

Thanks,
Todd

**Comment by rustygeldmacher** [comment]
Hi @tlinkner -- any chance you could put together a small example that demonstrates this problem? Maybe a few files in a gist? I can then work backwards from that and try and fix. Thanks!

**Comment by WanderingMatt** [comment]
I also just noticed this issue. Here is an example Gist.

https://gist.github.com/WanderingMatt/ac5a849740da5da509ca

In my example, the markdown inside the 'aside' contentblock is not being parsed. The content comes through as a single block of text.

![screenshot 2015-09-15 14 01 23](https://cloud.githubusercontent.com/assets/11926/9890029/6de00a4e-5bb2-11e5-9f2f-0c53a368b286.png)

**Comment by rustygeldmacher** [comment]
Nice, thanks @WanderingMatt -- I will use this as a starting point for checking into the issue.

**Comment by tlinkner** [comment]
@WanderingMatt's gist is a good example. Here's mine. Sorry I didn't get post it earlier. 

http://tlda.co/contentfor/

**Comment by rustygeldmacher** [comment]
@tlinkner @WanderingMatt -- I just pushed out jekyll-contentblocks 1.0.1 that should fix this issue. Please give it a try and let me know if it works.

**Comment by tlinkner** [comment]
Works for me. Thanks!

**Comment by WanderingMatt** [comment]
Sorry for the delayed response — was in Australia! Just verified this as well. Thanks a ton, @rustygeldmacher!
