### ISSUE TITLE
Do I need to restrict content blocks to a page

### ISSUE THREAD

**Issue by erikse** [rustygeldmacher/jekyll-contentblocks#16]
Like the sample in the README, I've created a ```_layouts/default.html``` file with:
```
    <div class="sidebar">
      {% contentblock sidebar %}
    </div>
```
and a pair of files that each declare their own sidebar content, the first ```page.md``` having
```
{% contentfor sidebar %}
* Some page content in a list
{% endcontentfor %}
```
and second ```test.md``` having
```
{% contentfor sidebar %}
* Some test content in a list
{% endcontentfor %}
```

When I build the site, in content in```page.html``` is fine:
```
<div class="sidebar">
  <ul>
    <li>Some page content in a list</li>
  </ul>
</div>
```
but the second ```test.html``` file contains the content for both sidebars:
```
<div class="sidebar">      
  <ul>
    <li>
      <p>Some page content in a list</p>
    </li>
    <li>
      <p>Some test content in a list</p>
    </li>
  </ul>
</div>
```
 so just wondering if there is something I need to do restrict that. Have pushed the sample project here https://github.com/erikse/jekyll_3_content_blocks

**Comment by rustygeldmacher** [comment]
Hi @erikse -- thanks so much for the detailed bug report and the example repo. I was able to reproduce this and confirm that this is a bug w/ jekyll_content_blocks and jekyll 3.1.1. I haven't done a formal test yet, but it does seem to work find on jekyll 3.0.x -- until I can get time to work out the cause, I'm afraid your workaround for the moment would be to use jekyll 3.0.x -- I'll update this ticket when I get some time to find a fix. Hope that helps!

**Comment by erikse** [comment]
Thanks @rustygeldmacher - that does help! I've changed to 3.0.0 and it all seems to fine in this version, thanks!

**Comment by jtbandes** [comment]
I ran into this issue too. Going to try downgrading to Jekyll to 3.0.x and hopefully that'll work. Thanks for a great plugin! :smile:

**Comment by rustygeldmacher** [comment]
Hi @erikse -- I just released a new version of jekyll-contentblocks that supports the latest Jekyll version. I tried it with your example repo and it worked. Please give it a try and let me know how it goes.

**Comment by erikse** [comment]
Hi @rustygeldmacher tried in a 3.1.2 version of Jekyl, looks good! Thanks for the quick update on this :+1:
