### ISSUE TITLE
Using variables for contentblock names

### ISSUE THREAD

**Issue by gitwn** [rustygeldmacher/jekyll-contentblocks#7]
Hi

I would like to define multiple blocks in an .md file and have the layout create them in the correct order automatically. I tried using YAML variables, but it seems that the Liquid variables does not get substituted in the {% contentblock %}

I tried this:

index.md

```
---
layout: default
sections:
  intro: Section 1 title
  help: Another title
---
{% contentfor intro %}
This is intro block
{% endcontentfor %}

{% contentfor help %}
HELP HELP
{% endcontentfor %}
```

default.html
```
{% for section in page.sections %}
  <li>
    {% contentblock section[0]  %}
    {% contentblock {{ section[0] }}  %}
    {% contentblock "section[0]"  %}
    {% contentblock 'section[0]'  %}
  </li>
{% endfor %}
```

Is there a way to achieve this?

Thanks.

**Comment by rustygeldmacher** [comment]
Hi @gitwn I did a little digging and I'm not sure Liquid supports this. The first parameter to the block tag would need to be interpreted as a variable and I didn't see a way to do that in the Liquid code. However, I'm not ruling out a creative pull request for this.
