### ISSUE TITLE
Support for Collections

### ISSUE THREAD

**Issue by turnavies** [rustygeldmacher/jekyll-contentblocks#8]
I can't get this plugin to work in combination with Jekyll Collections. It works fine when I avoid them. 
Tried on Jekyll 2.4.0, 2.5.3.

[Full stacktrace](https://gist.github.com/turnavies/b13144e60f8e3bc865e2#file-gistfile1-txt)

**Comment by rustygeldmacher** [comment]
Fixed in #9
